/**
 * @file    nx1_sm3_shader_cache.h
 * @brief   Shader Model 3.0 bytecode cache for the native D3D9 renderer.
 *
 * Generated by `XenosRecomp <in> <out> <include> --sm3 <this cache's .cpp>`.
 * Keyed by the same Xenos microcode hash as the DXIL cache, so a shader is
 * looked up by hashing the guest's post-patch microcode.
 */

#pragma once

#include <cstddef>
#include <cstdint>

enum Nx1Sm3Flags : uint32_t
{
    NX1_SM3_PIXEL_SHADER = 1u << 0,

    /// The shader uses relative addressing (`c[a0 + n]`), so its constant file
    /// could not be compacted: upload all 256 stage constants 1:1.
    NX1_SM3_UNCOMPACTED_CONSTANTS = 1u << 1,

    /// vs_3_0 has only 256 float registers and this shader needs every one, so
    /// `g_HalfPixelOffset` was dropped. The host must fold the half-pixel bias
    /// into the projection constants for draws using this shader.
    NX1_SM3_NEEDS_HOST_HALF_PIXEL = 1u << 2,
};

struct Nx1Sm3CacheEntry
{
    uint64_t hash;            ///< XXH3 of the Xenos microcode
    uint32_t bytecodeOffset;  ///< into the decompressed bytecode blob
    uint32_t bytecodeSize;    ///< 0 == cache miss, fall back to the translated path
    uint32_t remapOffset;     ///< into g_nx1Sm3ConstantRemap
    uint32_t remapCount;      ///< number of host constant registers used
    uint32_t flags;           ///< Nx1Sm3Flags
};

extern Nx1Sm3CacheEntry g_nx1Sm3CacheEntries[];
extern const size_t g_nx1Sm3CacheEntryCount;

/// `g_nx1Sm3ConstantRemap[entry.remapOffset + i]` is the guest ALU constant
/// register (stage-relative) that must be uploaded into host register `i`.
extern const uint16_t g_nx1Sm3ConstantRemap[];

extern const uint8_t g_compressedNx1Sm3Cache[];
extern const size_t g_nx1Sm3CacheCompressedSize;
extern const size_t g_nx1Sm3CacheDecompressedSize;
